# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: tailfed

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: checksums.txt

before:
  hooks:
    - go mod tidy

nightly:
  publish_release: false
  version_template: nightly
  tag_name: nightly

partial:
  by: target

builds:
  - id: client
    main: ./cmd/client
    binary: client
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm: [ "6", "7" ]
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

  - id: finalizer
    main: ./cmd/finalizer
    binary: bootstrap
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

  - id: initializer
    main: ./cmd/initializer
    binary: bootstrap
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

  - id: verifier
    main: ./cmd/verifier
    binary: bootstrap
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

  - id: generator
    main: ./cmd/generator
    binary: bootstrap
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

archives:
  - id: client
    ids: [ client ]
    formats: [ binary ]
    name_template: >-
      client_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: finalizer
    ids: [ finalizer ]
    formats: [ zip ]
    name_template: finalizer-{{ .Arch }}
    files: [ none* ]

  - id: initializer
    ids: [ initializer ]
    formats: [ zip ]
    name_template: initializer-{{ .Arch }}
    files: [ none* ]

  - id: verifier
    ids: [ verifier ]
    formats: [ zip ]
    name_template: verifier-{{ .Arch }}
    files: [ none* ]

  - id: generator
    ids: [ generator ]
    formats: [ zip ]
    name_template: generator-{{ .Arch }}
    files: [ none* ]

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --bundle=${signature}
      - ${artifact}
    artifacts: archive

sboms:
  - id: lambda
    artifacts: archive
  - id: client
    artifacts: binary
    ids: [ client ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

blobs:
  - provider: s3
    region: "{{ .Env.AWS_REGION }}"
    bucket: tailfed-artifacts
    directory: "{{ .Version }}"
    ids:
      - finalizer
      - initializer
      - verifier
      - generator
