# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: tailfed

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: client
    main: ./cmd/client
    env:
      - CGO_ENABLED=0

  - id: finalizer
    main: ./cmd/finalizer
    binary: finalizer
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

  - id: initializer
    main: ./cmd/initializer
    binary: initializer
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

  - id: verifier
    main: ./cmd/verifier
    binary: verifier
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -tags=lambda.norpc

archives:
  - id: client
    ids: [client]
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

  - id: finalizer
    ids: [ finalizer ]
    formats: [ zip ]
    name_template: "{{ .Binary }}-{{ .Arch }}"
    files: [ none* ]

  - id: initializer
    ids: [ initializer ]
    formats: [ zip ]
    name_template: "{{ .Binary }}-{{ .Arch }}"
    files: [ none* ]

  - id: verifier
    ids: [ verifier ]
    formats: [ zip ]
    name_template: "{{ .Binary }}-{{ .Arch }}"
    files: [ none* ]

signs:
  - cmd: cosign
    args:
      - sign-blob
      - --yes
      - --bundle=${artifact}.sig
      - --output-signature=${signature}
      - ${artifact}
    artifacts: all

sboms:
  - artifacts: binary

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).

blobs:
  - provider: s3
    region: "{{ .Env.AWS_REGION }}"
    bucket: tailfed-artifacts
    directory: "{{ .Version }}"
    ids:
      - finalizer
      - initializer
      - verifier
